---
apiVersion: v1
kind: Service
metadata:
  name: appinfo-svc
  labels:
    app: appinfo
spec:
  type: NodePort
  selector:
    app: appinfo
  ports:
  - protocol: TCP
    port: 8080
    name: http