apiVersion: apps/v1
kind: Deployment
metadata:
  name: appinfo-deployment
  labels:
    app: appinfo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appinfo
  template:
    metadata:
      labels:
        app: appinfo
    spec:
      containers:
        - name: appinfo
          image: bharathpantala/appinfo:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: appinfo-secrets
                  key: DB_NAME
            - name: DB_PWD
              valueFrom:
                secretKeyRef:
                  name: appinfo-secrets
                  key: DB_PWD
